import { app, BrowserWindow, ipcMain, dialog, shell, session, Menu, screen } from 'electron'
import path from 'path'
import fs from 'fs'
import os from 'os'
import { YtDlpService } from './services/YtDlpService'
import { DependencyManager } from './services/DependencyManager'
import { PreferencesService } from './services/PreferencesService'
import type { DownloadItem, DownloadOptions } from '../src/types'

let win: BrowserWindow | null = null
let ytDlp: YtDlpService
let deps: DependencyManager
let prefs: PreferencesService

const isDev = !app.isPackaged

function createWindow() {
  const savedBounds = prefs.get('window.bounds', null)
  const wasMaximized = prefs.get('window.isMaximized', false)

  const windowOpts: Electron.BrowserWindowConstructorOptions = {
    width: savedBounds?.width ?? 1100,
    height: savedBounds?.height ?? 900,
    minWidth: 900,
    minHeight: 700,
    icon: path.join(__dirname, '../resources/icons/256.png'),
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      devTools: true,
    },
  }

  if (savedBounds && savedBounds.x !== undefined && savedBounds.y !== undefined) {
    const bounds = { x: savedBounds.x, y: savedBounds.y, width: savedBounds.width, height: savedBounds.height }
    if (isBoundsVisibleOnAnyDisplay(bounds)) {
      windowOpts.x = bounds.x
      windowOpts.y = bounds.y
    }
  }

  win = new BrowserWindow(windowOpts)

  if (wasMaximized && win) {
    win.maximize()
  }

  win.on('close', () => {
    if (win) {
      const isMaximized = win.isMaximized()
      const bounds = isMaximized ? win.getNormalBounds() : win.getBounds()
      prefs.set('window.bounds', { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height })
      prefs.set('window.isMaximized', isMaximized)
      prefs.save()
    }
  })

  if (isDev) {
    win.loadURL('http://localhost:5173')
  } else {
    win.loadFile(path.join(__dirname, '../dist/index.html'))
  }
}

function isBoundsVisibleOnAnyDisplay(bounds: { x: number; y: number; width: number; height: number }): boolean {
  for (const display of screen.getAllDisplays()) {
    const { x, y, width, height } = display.workArea
    if (bounds.x < x + width && bounds.x + bounds.width > x &&
        bounds.y < y + height && bounds.y + bounds.height > y) {
      return true
    }
  }
  return false
}

// ─── IPC: Downloads ────────────────────────────────────────────

ipcMain.handle('download:start', async (_event, item: DownloadItem, options: DownloadOptions) => {
  if (prefs.getBoolean('browser.cookies.enabled', true)) {
    const urlObj = new URL(item.url)
    const rootUrl = `${urlObj.protocol}//${urlObj.hostname}`
    await session.defaultSession.cookies.flushStore()
    const cookies = await session.defaultSession.cookies.get({ url: rootUrl })
    console.log(`[main] cookies for ${rootUrl}: ${cookies.length} found`)
    if (cookies.length > 0) {
      const cookieLines = cookies.map((c) => {
        const domain = c.domain || urlObj.hostname
        const flag = (domain.startsWith('.') || c.domain?.startsWith('.')) ? 'TRUE' : 'FALSE'
        const p = c.path || '/'
        const secure = c.secure ? 'TRUE' : 'FALSE'
        const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0
        return `${domain}\t${flag}\t${p}\t${secure}\t${expiry}\t${c.name}\t${c.value}`
      })
      const header = '# Netscape HTTP Cookie File\n# Generated by HVD\n\n'
      const tempFile = path.join(os.tmpdir(), 'hvd-yt-cookies.txt')
      fs.writeFileSync(tempFile, header + cookieLines.join('\n') + '\n', 'utf8')
      console.log(`[main] wrote ${cookies.length} cookies to ${tempFile}`)
      options.cookiesFile = tempFile
    } else {
      console.log(`[main] no cookies found for ${rootUrl} — download will proceed without auth`)
    }
  }
  ytDlp.startDownload(item, options)
})

ipcMain.handle('download:cancel', async (_event, id: string) => {
  ytDlp.cancelDownload(id)
})

ipcMain.handle('download:extract-title', async (_event, url: string, browser?: string) => {
  return ytDlp.extractTitle(url, browser)
})

// ─── IPC: Dependencies ──────────────────────────────────────────

ipcMain.handle('deps:check-ytdlp', async () => {
  const available = await ytDlp.isAvailable()
  let version: string | undefined
  let isRecent: boolean | undefined
  if (available) {
    version = await ytDlp.getVersion()
    isRecent = await ytDlp.isVersionRecent()
  }
  return { available, version, isRecent }
})

ipcMain.handle('deps:check-ffmpeg', async () => {
  return ytDlp.isFFmpegAvailable()
})

ipcMain.handle('deps:check-deno', async () => {
  return ytDlp.isDenoAvailable()
})

ipcMain.handle('deps:download-ytdlp', async () => {
  await deps.download('ytdlp', () => {})
})

ipcMain.handle('deps:download-ffmpeg', async () => {
  await deps.download('ffmpeg', () => {})
})

ipcMain.handle('deps:download-deno', async () => {
  await deps.download('deno', () => {})
})

ipcMain.handle('deps:open-folder', async (_event, type: string) => {
  shell.openPath(deps.getBinDirectory())
})

ipcMain.handle('deps:get-ytdlp-version', async () => {
  return ytDlp.getVersion()
})

// ─── IPC: Preferences ───────────────────────────────────────────

ipcMain.handle('prefs:get', async (_event, key: string) => {
  return prefs.get(key)
})

ipcMain.handle('prefs:set', async (_event, key: string, value: any) => {
  prefs.set(key, value)
})

ipcMain.handle('prefs:getAll', async () => {
  return prefs.getAll()
})

// ─── IPC: Dialog ────────────────────────────────────────────────

ipcMain.handle('dialog:open-folder', async () => {
  console.log('[main] dialog:open-folder called, win:', !!win)
  if (!win) return null
  const result = await dialog.showOpenDialog(win, {
    properties: ['openDirectory'],
  })
  console.log('[main] dialog result:', result.canceled, result.filePaths)
  return result.canceled ? null : result.filePaths[0]
})

ipcMain.handle('dialog:alert', async (_event, opts: { title: string; message: string; type?: string; buttons?: string[] }) => {
  if (!win) return -1
  const result = await dialog.showMessageBox(win, {
    title: opts.title,
    message: opts.message,
    type: (opts.type as any) || 'info',
    buttons: opts.buttons || ['OK'],
    defaultId: 0,
  })
  return result.response
})

// ─── IPC: App ────────────────────────────────────────────────────

ipcMain.handle('app:get-locale', async () => {
  return app.getLocale()
})

ipcMain.handle('app:open-path', async (_event, filePath: string) => {
  shell.openPath(filePath)
})

ipcMain.handle('app:restart', async () => {
  app.relaunch()
  app.exit(0)
})

// ─── IPC: YouTube Authentication ─────────────────────────────────

ipcMain.handle('app:login-url', async (_event, url: string) => {
  const loginWin = new BrowserWindow({
    width: 900,
    height: 700,
    title: 'Log in',
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  })
  await loginWin.loadURL(url)
  return new Promise((resolve) => {
    loginWin.on('close', () => resolve(true))
  })
})

ipcMain.handle('app:get-cookies-file', async () => {
  const cookies = await session.defaultSession.cookies.get({ url: 'https://www.youtube.com' })
  if (cookies.length === 0) return null

  // Write Netscape-format cookies file for yt-dlp
  const cookieLines = cookies.map((c) => {
    const domain = c.domain || '.youtube.com'
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const path = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0
    return `${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`
  })
  const header = '# Netscape HTTP Cookie File\n# Generated by HVD\n\n'
  const tempFile = path.join(os.tmpdir(), 'hvd-yt-cookies.txt')
  fs.writeFileSync(tempFile, header + cookieLines.join('\n') + '\n', 'utf8')
  return tempFile
})

// ─── Shutdown ────────────────────────────────────────────────────

function shutdown() {
  ytDlp.cancelAll()
  prefs.save()
}

app.on('before-quit', shutdown)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.whenReady().then(() => {
  ytDlp = new YtDlpService()
  deps = new DependencyManager()
  prefs = new PreferencesService()
  Menu.setApplicationMenu(null)
  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow()
    }
  })
})